# Generated by Django 4.1 on 2023-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
