# Generated by Django 4.1 on 2023-02-21 10:58

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Заголовок'),
        ),
    ]
