# Generated by Django 4.1 on 2023-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_name_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube url'),
        ),
    ]
