# Generated by Django 4.1 on 2023-02-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_products_main_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='main_products',
            new_name='main',
        ),
    ]
