# Generated by Django 4.1 on 2023-02-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_main_products_products_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subtile',
            new_name='subtitle',
        ),
    ]
