# Generated by Django 4.1 on 2023-02-25 09:05

import admins.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_subtile_products_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='shortapplication',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fieldofactivity'),
        ),
    ]
