# Generated by Django 4.1 on 2023-02-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_fieldofactivity_shortapplication_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofactivity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
