# Generated by Django 4.1 on 2023-02-28 09:43

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_fieldofactivity_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
